version: "3.9"
services:
  app:
    build:
      context: .
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped
