spring:
  application:
    name: s19.challenge

  datasource:
    url: jdbc:postgresql://${NEON_HOST}:5432/${NEON_DB}?sslmode=require
    username: ${NEON_USER}
    password: ${NEON_PASSWORD}
    name: spring-blog


  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: twitter

  web:
    cors:
      allowed-origins:
        - http://localhost:3000
        - https://twitter-clone-frontend-production-5591.up.railway.app
      allowed-methods: [GET, POST, PUT, DELETE, OPTIONS]
      allowed-headers: ["*"]
      allow-credentials: true

server:
  port: ${APP_PORT:9000}
  servlet:
    session:
      cookie:
        path: /
        same-site: none
        secure: true
  forward-headers-strategy: framework
