spring:
  profiles:
    active: docker
  config:
    import: optional:file:.env[.properties]
  application:
    name: s19.challenge
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: twitter

server:
  port: ${APP_PORT}
  servlet:
    context-path: /workintech
    session:
      cookie:
        path: /
        same-site: Lax
        secure: false

security:
  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.workitech.s19.challenge: DEBUG
