spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}?sslmode=require
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: spring-blog

  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate.default_schema: twitter