spring:
  application:
    name: s19.challenge
  datasource:
    url: jdbc:postgresql://${NEON_HOST}:5432/${NEON_DB}?sslmode=require&currentSchema=twitter
    username: ${NEON_USER}
    password: ${NEON_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: twitter

server:
  port: ${APP_PORT}
  servlet:
    context-path: /workintech
    session:
      cookie:
        path: /
        same-site: lax
        secure: false

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.workitech.s19.challenge.security: DEBUG
    com.workitech.s19.challenge.util: DEBUG
