spring:
  application:
    name: s19.challenge
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 341344

server:
  port: 9000
  servlet:
    context-path: /workintech
    session:
      cookie:
        path: /
        same-site: lax
        secure: false


