spring:
  datasource:
    url: jdbc:postgresql://${NEON_HOST}:5432/${NEON_DB}?sslmode=require&currentSchema=twitter
    username: ${NEON_USER}
    password: ${NEON_PASSWORD}

server:
  servlet:
    session:
      cookie:
        same-site: None
        secure: true
